export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const RESET_REGISTER = "RESET_REGISTER";

export const FORGOT_PASSWORD_REQUESTED = "FORGOT_PASSWORD_REQUESTED";
export const FORGOT_PASSWORD_SUCCEEDED = "FORGOT_PASSWORD_SUCCEEDED";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

export const RESET_PASSWORD_REQUESTED = "RESET_PASSWORD_REQUESTED";
export const RESET_PASSWORD_SUCCEEDED = "RESET_PASSWORD_SUCCEEDED";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const FETCH_COUNTRY_CODES_REQUESTED = "FETCH_COUNTRY_CODES_REQUESTED";
export const FETCH_COUNTRY_CODES_SUCCEEDED = "FETCH_COUNTRY_CODES_SUCCEEDED";
export const FETCH_COUNTRY_CODES_FAILED = "FETCH_COUNTRY_CODES_FAILED";

export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_SUCCEEDED = "REGISTER_SUCCEEDED";
export const REGISTER_FAILED = "REGISTER_FAILED";
