export const FETCH_MATERIAL_REQUESTED = "FETCH_MATERIAL_REQUESTED";
export const FETCH_MATERIAL_SUCCEEDED = "FETCH_MATERIAL_SUCCEEDED";
export const FETCH_MATERIAL_FAILED = "FETCH_MATERIAL_FAILED";

export const UPDATE_MATERIAL_REQUESTED = "UPDATE_MATERIAL_REQUESTED";
export const UPDATE_MATERIAL_SUCCEEDED = "UPDATE_MATERIAL_SUCCEEDED";
export const UPDATE_MATERIAL_FAILED = "UPDATE_MATERIAL_FAILED";

