export const FETCH_QUIZ_DETAILS_REQUESTED = "FETCH_QUIZ_DETAILS_REQUESTED";
export const FETCH_QUIZ_DETAILS_SUCCEEDED = "FETCH_QUIZ_DETAILS_SUCCEEDED";
export const FETCH_QUIZ_DETAILS_FAILED = "FETCH_QUIZ_DETAILS_FAILED";

export const SET_ACTIVE_QUIZ = "SET_ACTIVE_QUIZ";

export const FETCH_QUIZ_QUESTIONS_REQUESTED = "FETCH_QUIZ_QUESTIONS_REQUESTED";
export const FETCH_QUIZ_QUESTIONS_SUCCEEDED = "FETCH_QUIZ_QUESTIONS_SUCCEEDED";
export const FETCH_QUIZ_QUESTIONS_FAILED = "FETCH_QUIZ_QUESTIONS_FAILED";

export const FETCH_QUIZ_RESULT_REQUESTED = "FETCH_QUIZ_RESULT_REQUESTED";
export const FETCH_QUIZ_RESULT_SUCCEEDED = "FETCH_QUIZ_RESULT_SUCCEEDED";
export const FETCH_QUIZ_RESULT_FAILED = "FETCH_QUIZ_RESULT_FAILED";

export const FETCH_ATTEMPT_DETAILS_REQUESTED =
  "FETCH_ATTEMPT_DETAILS_REQUESTED";
export const FETCH_ATTEMPT_DETAILS_SUCCEEDED =
  "FETCH_ATTEMPT_DETAILS_SUCCEEDED";
export const FETCH_ATTEMPT_DETAILS_FAILED = "FETCH_ATTEMPT_DETAILS_FAILED";

export const FETCH_ALL_QUIZ_ATTEMPTS_REQUESTED =
  "FETCH_ALL_QUIZ_ATTEMPTS_REQUESTED";
export const FETCH_ALL_QUIZ_ATTEMPTS_SUCCEEDED =
  "FETCH_ALL_QUIZ_ATTEMPTS_SUCCEEDED";
export const FETCH_ALL_QUIZ_ATTEMPTS_FAILED = "FETCH_ALL_QUIZ_ATTEMPTS_FAILED";

export const SET_ANSWER_TO_QUESTION = "SET_ANSWER_TO_QUESTION";

export const SHOW_QUIZ_ANSWERS = "SHOW_QUIZ_ANSWERS";
export const HIDE_QUIZ_ANSWERS = "HIDE_QUIZ_ANSWERS";

export const QUIZ_TIMER_START = "QUIZ_TIMER_START";
export const QUIZ_TIMER_STOP = "QUIZ_TIMER_STOP";
export const QUIZ_TIMER_TICK = "QUIZ_TIMER_TICK";

export const REMOVE_ACTIVE_QUIZ = "REMOVE_ACTIVE_QUIZ";

export const RESET_ACTIVE_QUIZ = "RESET_ACTIVE_QUIZ";

export const SHOW_QUIZ_RESULT = "SHOW_QUIZ_RESULT";

export const SET_QUIZ_OVER = "SET_QUIZ_OVER";
export const SET_ATTEMPT_REFERENCE = "SET_ATTEMPT_REFERENCE";
export const UPDATE_QUIZ_ATTEMPT = "UPDATE_QUIZ_ATTEMPT";
