export const FETCH_COURSE_MODULES_REQUESTED = "FETCH_COURSE_MODULES_REQUESTED";
export const FETCH_COURSE_MODULES_SUCCEEDED = "FETCH_COURSE_MODULES_SUCCEEDED";
export const FETCH_COURSE_MODULES_FAILED = "FETCH_COURSE_MODULES_FAILED";

export const FETCH_COURSE_MODULE_REQUESTED = "FETCH_COURSE_MODULE_REQUESTED";
export const FETCH_COURSE_MODULE_SUCCEEDED = "FETCH_COURSE_MODULE_SUCCEEDED";
export const FETCH_COURSE_MODULE_FAILED = "FETCH_COURSE_MODULE_FAILED";

export const UPDATE_VIEW_COUNT = "UPDATE_VIEW_COUNT";

export const UPDATE_SOLVE_STATUS = "UPDATE_SOLVE_STATUS";

export const UPDATE_QUIZ_COMPLETION = "UPDATE_QUIZ_COMPLETION";
