export const FETCH_COLLABORATORS_REQUESTED = "FETCH_COLLABORATORS_REQUESTED";
export const FETCH_COLLABORATORS_SUCCEEDED = "FETCH_COLLABORATORS_SUCCEEDED";
export const FETCH_COLLABORATORS_FAILED = "FETCH_COLLABORATORS_FAILED";

export const FETCH_ALL_USERS_REQUESTED = "FETCH_ALL_USERS_REQUESTED";
export const FETCH_ALL_USERS_SUCCEEDED = "FETCH_ALL_USERS_SUCCEEDED";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";

export const ADD_COLLABORATORS_REQUESTED = "ADD_COLLABORATORS_REQUESTED";
export const ADD_COLLABORATORS_SUCCEEDED = "ADD_COLLABORATORS_SUCCEEDED";
export const ADD_COLLABORATORS_FAILED = "ADD_COLLABORATORS_FAILED";

export const GET_SHAREABLE_LINK_REQUESTED = "GET_SHAREABLE_LINK_REQUESTED";
export const GET_SHAREABLE_LINK_SUCCEEDED = "GET_SHAREABLE_LINK_SUCCEEDED";
export const GET_SHAREABLE_LINK_FAILED = "GET_SHAREABLE_LINK_FAILED";

export const RESET_SHAREABLE_LINK = "RESET_SHAREABLE_LINK";

export const GET_SHARED_DASHBOARD_REQUESTED = "GET_SHARED_DASHBOARD_REQUESTED";
export const GET_SHARED_DASHBOARD_SUCCEEDED = "GET_SHARED_DASHBOARD_SUCCEEDED";
export const GET_SHARED_DASHBOARD_FAILED = "GET_SHARED_DASHBOARD_FAILED";
