export const INITIATE_EDIT_COURSE = "INITIATE_EDIT_COURSE";

export const SET_MODULE_REFERENCE = "SET_MODULE_REFERENCE";

export const SET_MODULE_CONTENT_REFERENCE = "SET_MODULE_CONTENT_REFERENCE";

export const SAVE_MODULE_INPUTS_DATA = "SAVE_MODULE_INPUTS_DATA";

export const RESET_MODULE_INPUTS_DATA = "RESET_MODULE_INPUTS_DATA";

export const SET_LOADING = "SET_LOADING";
export const RESET_LOADING = "RESET_LOADING";
