export const FETCH_WEBINARS_REQUESTED = "FETCH_WEBINARS_REQUESTED";
export const FETCH_WEBINARS_SUCCEEDED = "FETCH_WEBINARS_SUCCEEDED";
export const FETCH_WEBINARS_FAILED = "FETCH_WEBINARS_FAILED";

export const ENROL_WEBINAR_REQUESTED = "ENROL_WEBINAR_REQUESTED";
export const ENROL_WEBINAR_SUCCEEDED = "ENROL_WEBINAR_SUCCEEDED";
export const ENROL_WEBINAR_FAILED = "ENROL_WEBINAR_FAILED";

export const UNENROL_WEBINAR_REQUESTED = "UNENROL_WEBINAR_REQUESTED";
export const UNENROL_WEBINAR_SUCCEEDED = "UNENROL_WEBINAR_SUCCEEDED";
export const UNENROL_WEBINAR_FAILED = "UNENROL_WEBINAR_FAILED";
