export const PIN_OUTPUT_REQUESTED = "PIN_OUTPUT_REQUESTED";
export const PIN_OUTPUT_SUCCEEDED = "PIN_OUTPUT_SUCCEEDED";
export const PIN_OUTPUT_FAILED = "PIN_OUTPUT_FAILED";

export const ARRANGE_DASHBOARD_ITEMS_REQUESTED =
  "ARRANGE_DASHBOARD_ITEMS_REQUESTED";
export const ARRANGE_DASHBOARD_ITEMS_SUCCEEDED =
  "ARRANGE_DASHBOARD_ITEMS_SUCCEEDED";
export const ARRANGE_DASHBOARD_ITEMS_FAILED = "ARRANGE_DASHBOARD_ITEMS_FAILED";

export const UPDATE_DASHBOARD_ITEM_REQUESTED =
  "UPDATE_DASHBOARD_ITEM_REQUESTED";
export const UPDATE_DASHBOARD_ITEM_SUCCEEDED =
  "UPDATE_DASHBOARD_ITEM_SUCCEEDED";
export const UPDATE_DASHBOARD_ITEM_FAILED = "UPDATE_DASHBOARD_ITEM_FAILED";

export const ADD_DASHBOARD_ITEM_REQUESTED = "ADD_DASHBOARD_ITEM_REQUESTED";
export const ADD_DASHBOARD_ITEM_SUCCEEDED = "ADD_DASHBOARD_ITEM_SUCCEEDED";
export const ADD_DASHBOARD_ITEM_FAILED = "ADD_DASHBOARD_ITEM_FAILED";

export const REMOVE_DASHBOARD_ITEM_REQUESTED =
  "REMOVE_DASHBOARD_ITEM_REQUESTED";
export const REMOVE_DASHBOARD_ITEM_SUCCEEDED =
  "REMOVE_DASHBOARD_ITEM_SUCCEEDED";
export const REMOVE_DASHBOARD_ITEM_FAILED = "REMOVE_DASHBOARD_ITEM_FAILED";

export const GET_DASHBOARD_ITEMS_REQUESTED = "GET_DASHBOARD_ITEMS_REQUESTED";
export const GET_DASHBOARD_ITEMS_SUCCEEDED = "GET_DASHBOARD_ITEMS_SUCCEEDED";
export const GET_DASHBOARD_ITEMS_FAILED = "GET_DASHBOARD_ITEMS_FAILED";

export const ADD_TO_DASHBOARD = "ADD_TO_DASHBOARD";
export const CHANGE_TEXT = "CHANGE_TEXT";
export const ARRANGE_DASHBOARD_ITEMS = "ARRANGE_DASHBOARD_ITEMS";
export const ADD_TITLE_TO_DASHBOARD_ITEM = "ADD_TITLE_TO_DASHBOARD_ITEM";
