export const UserRole = {
  LEARNER: "LEARNER",
  COURSE_CREATOR: "COURSE_CREATOR",
  ADMIN: "ADMIN",
  COURSE_REVIEWER: "COURSE_REVIEWER",
  ADMIN_TENANT: "ADMIN_TENANT",
  ADMIN_READONLY: "ADMIN_READONLY",
  SUPER_ADMIN: "SUPER_ADMIN",
  SUPER_ADMIN_TENANT: "SUPER_ADMIN_TENANT"
};
