export const FETCH_HACKATHON_LIST_REQUESTED = "FETCH_HACKATHON_LIST_REQUESTED";
export const FETCH_HACKATHON_LIST_SUCCEEDED = "FETCH_HACKATHON_LIST_SUCCEEDED";
export const FETCH_HACKATHON_LIST_FAILED = "FETCH_HACKATHON_LIST_FAILED";

export const UPDATE_HACKATHON = "UPDATE_HACKATHON";

export const FETCH_HACKATHON_QUIZ_INSTRUCTIONS_REQUESTED =
  "FETCH_HACKATHON_QUIZ_INSTRUCTIONS_REQUESTED";
export const FETCH_HACKATHON_QUIZ_INSTRUCTIONS_SUCCEEDED =
  "FETCH_HACKATHON_QUIZ_INSTRUCTIONS_SUCCEEDED";
export const FETCH_HACKATHON_QUIZ_INSTRUCTIONS_FAILED =
  "FETCH_HACKATHON_QUIZ_INSTRUCTIONS_FAILED";

export const FETCH_HACKATHON_QUIZ_REQUESTED = "FETCH_HACKATHON_QUIZ_REQUESTED";
export const FETCH_HACKATHON_QUIZ_SUCCEEDED = "FETCH_HACKATHON_QUIZ_SUCCEEDED";
export const FETCH_HACKATHON_QUIZ_FAILED = "FETCH_HACKATHON_QUIZ_FAILED";

export const FETCH_HACKATHON_QUIZ_OPTION_SELECTED =
  "FETCH_HACKATHON_QUIZ_OPTION_SELECTED";

export const SET_ACTIVE_QUIZ_FULL_SCREEN = "SET_ACTIVE_QUIZ_FULL_SCREEN";
export const MINIMIZE_ACTIVE_QUIZ = "MINIMIZE_ACTIVE_QUIZ";

export const SUBMISSION_LIST = "SUBMISSION_LIST";
