export const FETCH_CASE_DETAILS_REQUESTED = "FETCH_CASE_DETAILS_REQUESTED";
export const FETCH_CASE_DETAILS_SUCCEEDED = "FETCH_CASE_DETAILS_SUCCEEDED";
export const FETCH_CASE_DETAILS_FAILED = "FETCH_CASE_DETAILS_FAILED";

export const RESET_CASE = "RESET_CASE";

export const FETCH_SCENARIO_DETAILS_REQUESTED =
  "FETCH_SCENARIO_DETAILS_REQUESTED";
export const FETCH_SCENARIO_DETAILS_SUCCEEDED =
  "FETCH_SCENARIO_DETAILS_SUCCEEDED";
export const FETCH_SCENARIO_DETAILS_FAILED = "FETCH_SCENARIO_DETAILS_FAILED";

export const FETCH_CASE_COLLABORATORS_REQUESTED =
  "FETCH_CASE_COLLABORATORS_REQUESTED";
export const FETCH_CASE_COLLABORATORS_SUCCEEDED =
  "FETCH_CASE_COLLABORATORS_SUCCEEDED";
export const FETCH_CASE_COLLABORATORS_FAILED =
  "FETCH_CASE_COLLABORATORS_FAILED";

export const FETCH_CASE_REQUESTED = "FETCH_CASE_REQUESTED";
export const FETCH_CASE_SUCCEEDED = "FETCH_CASE_SUCCEEDED";
export const FETCH_CASE_FAILED = "FETCH_CASE_FAILED";

export const FETCH_CASE_MATERIAL_REQUESTED = "FETCH_CASE_MATERIAL_REQUESTED";
export const FETCH_CASE_MATERIAL_SUCCEEDED = "FETCH_CASE_MATERIAL_SUCCEEDED";
export const FETCH_CASE_MATERIAL_FAILED = "FETCH_CASE_MATERIAL_FAILED";

export const EDIT_CASE_REQUESTED = "EDIT_CASE_REQUESTED";
export const EDIT_CASE_SUCCEEDED = "EDIT_CASE_SUCCEEDED";
export const EDIT_CASE_FAILED = "EDIT_CASE_FAILED";

export const DELETE_CASE_REQUESTED = "DELETE_CASE_REQUESTED";
export const DELETE_CASE_SUCCEEDED = "DELETE_CASE_SUCCEEDED";
export const DELETE_CASE_FAILED = "DELETE_CASE_FAILED";

export const FETCH_CASES_REQUESTED = "FETCH_CASES_REQUESTED";
export const FETCH_CASES_SUCCEEDED = "FETCH_CASES_SUCCEEDED";
export const FETCH_CASES_FAILED = "FETCH_CASES_FAILED";

export const FETCH_SAMPLE_CASES_REQUESTED = "FETCH_SAMPLE_CASES_REQUESTED";
export const FETCH_SAMPLE_CASES_SUCCEEDED = "FETCH_SAMPLE_CASES_SUCCEEDED";
export const FETCH_SAMPLE_CASES_FAILED = "FETCH_SAMPLE_CASES_FAILED";

export const FETCH_ALL_CASES_REQUESTED = "FETCH_ALL_CASES_REQUESTED";
export const FETCH_ALL_CASES_SUCCEEDED = "FETCH_ALL_CASES_SUCCEEDED";
export const FETCH_ALL_CASES_FAILED = "FETCH_ALL_CASES_FAILED";

export const ADD_DATASETS = "ADD_DATASETS";

export const FETCH_CASE_CATEGORIES_REQUESTED =
  "FETCH_CASE_CATEGORIES_REQUESTED";
export const FETCH_CASE_CATEGORIES_SUCCEEDED =
  "FETCH_CASE_CATEGORIES_SUCCEEDED";
export const FETCH_CASE_CATEGORIES_FAILED = "FETCH_CASE_CATEGORIES_FAILED";

export const CREATE_PROBLEM_REQUESTED = "CREATE_PROBLEM_REQUESTED";
export const CREATE_PROBLEM_SUCCEEDED = "CREATE_PROBLEM_SUCCEEDED";
export const CREATE_PROBLEM_FAILED = "CREATE_PROBLEM_FAILED";

export const CREATE_CASE_REQUESTED = "CREATE_CASE_REQUESTED";
export const CREATE_CASE_SUCCEEDED = "CREATE_CASE_SUCCEEDED";
export const CREATE_CASE_FAILED = "CREATE_CASE_FAILED";

export const GET_CASE_RECOMMENDATIONS_REQUESTED =
  "GET_CASE_RECOMMENDATIONS_REQUESTED";
export const GET_CASE_RECOMMENDATIONS_SUCCEEDED =
  "GET_CASE_RECOMMENDATIONS_SUCCEEDED";
export const GET_CASE_RECOMMENDATIONS_FAILED =
  "GET_CASE_RECOMMENDATIONS_FAILED";

export const SELECT_RECOMMENDATIONS = "SELECT_RECOMMENDATIONS";

export const PIN_OUTPUT_STEP = "PIN_OUTPUT_STEP";

export const FETCH_STEP_DATASET_CSV_REQUESTED =
  "FETCH_STEP_DATASET_CSV_REQUESTED";
export const FETCH_STEP_DATASET_CSV_SUCCEEDED =
  "FETCH_STEP_DATASET_CSV_SUCCEEDED";

export const EDIT_CASE_OVERVIEW_SUCCEEDED = "EDIT_CASE_OVERVIEW_SUCCEEDED";
export const UPDATE_CASE_OVERVIEW = "UPDATE_CASE_OVERVIEW";


export const EXTRACT_AND_DEPLOY_REQUESTED = "EXTRACT_AND_DEPLOY_REQUESTED";
export const EXTRACT_AND_DEPLOY_SUCCEEDED = "EXTRACT_AND_DEPLOY_SUCCEEDED";
export const EXTRACT_AND_DEPLOY_FAILED = "EXTRACT_AND_DEPLOY_FAILED";

export const CLONE_CASE_REQUESTED = "CLONE_CASE_REQUESTED";
export const CLONE_CASE_SUCCEEDED = "CLONE_CASE_SUCCEEDED";
export const CLONE_CASE_FAILED = "CLONE_CASE_FAILED";

export const RESET_EXTRACT_AND_DEPLOY = "RESET_EXTRACT_AND_DEPLOY";

export const ADD_DUPLICATED_SCENARIO = "ADD_DUPLICATED_SCENARIO";

export const SET_CLONE_CASE_NAME = "SET_CLONE_CASE_NAME";

export const UPDATE_SCENARIO_DATASETS = "UPDATE_SCENARIO_DATASETS";

